package com.mycompany.model;
// Generated 30/10/2017 04:00:46 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comentarios generated by hbm2java
 */
public class Comentarios  implements java.io.Serializable {


     private Integer id;
     private Resenas resenas;
     private Usuarios usuarios;
     private String comentario;
     private Date fecha;

    public Comentarios() {
    }

	
    public Comentarios(Resenas resenas, Usuarios usuarios) {
        this.resenas = resenas;
        this.usuarios = usuarios;
    }
    public Comentarios(Resenas resenas, Usuarios usuarios, String comentario, Date fecha) {
       this.resenas = resenas;
       this.usuarios = usuarios;
       this.comentario = comentario;
       this.fecha = fecha;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Resenas getResenas() {
        return this.resenas;
    }
    
    public void setResenas(Resenas resenas) {
        this.resenas = resenas;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


