package com.mycompany.model;
// Generated 30/10/2017 04:00:46 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Peliculas generated by hbm2java
 */
public class Peliculas  implements java.io.Serializable {


     private Integer id;
     private Date fechaDeEstreno;
     private String poster;
     private String resena;
     private String sinopsis;
     private String titulo;
     private Set<Resenas> resenases = new HashSet<Resenas>(0);

    public Peliculas() {
    }

    public Peliculas(Date fechaDeEstreno, String poster, String resena, String sinopsis, String titulo, Set<Resenas> resenases) {
       this.fechaDeEstreno = fechaDeEstreno;
       this.poster = poster;
       this.resena = resena;
       this.sinopsis = sinopsis;
       this.titulo = titulo;
       this.resenases = resenases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getFechaDeEstreno() {
        return this.fechaDeEstreno;
    }
    
    public void setFechaDeEstreno(Date fechaDeEstreno) {
        this.fechaDeEstreno = fechaDeEstreno;
    }
    public String getPoster() {
        return this.poster;
    }
    
    public void setPoster(String poster) {
        this.poster = poster;
    }
    public String getResena() {
        return this.resena;
    }
    
    public void setResena(String resena) {
        this.resena = resena;
    }
    public String getSinopsis() {
        return this.sinopsis;
    }
    
    public void setSinopsis(String sinopsis) {
        this.sinopsis = sinopsis;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Set<Resenas> getResenases() {
        return this.resenases;
    }
    
    public void setResenases(Set<Resenas> resenases) {
        this.resenases = resenases;
    }




}


