package com.mycompany.model;
// Generated 30/10/2017 04:00:46 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer id;
     private String contrasena;
     private String email;
     private String nombre;
     private Set<Comentarios> comentarioses = new HashSet<Comentarios>(0);

    public Usuarios() {
    }

    public Usuarios(String contrasena, String email, String nombre, Set<Comentarios> comentarioses) {
       this.contrasena = contrasena;
       this.email = email;
       this.nombre = nombre;
       this.comentarioses = comentarioses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Comentarios> getComentarioses() {
        return this.comentarioses;
    }
    
    public void setComentarioses(Set<Comentarios> comentarioses) {
        this.comentarioses = comentarioses;
    }




}


